spring:
  # redis 配置
  redis:
    # redis一共16个库，本次项目使用第10个
    database: 10
    host: 172.16.253.111
    port: 3379
    # 超时时间 5s
    timeout: 5000ms
    password: 123456
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接