version:
  api: api
  v: v1
spring:
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 172.16.253.110:8848
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 用户服务网关配置
        # 采用自定义路由 ID (有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters)
        - id: provider-user
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://provider-user
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # 路径匹配，以 api 开头，直接配置是不生效的，看 filters 配置
            - Path=/user/**
            - Path=/web/user/**
        # 认证服务网关配置
        - id: provider-oauth2
          uri: lb://provider-oauth2
          predicates:
            - Path=/auth/**
            - Path=/web/auth/**
        # 通用服务网关配置
        - id: provider-cloud
          uri: lb://provider-cloud
          predicates:
            - Path=/cloud/**
            - Path=/web/cloud/**
        # 后台管理服务网关配置
        - id: consumer-admin
          uri: lb://consumer-admin
          predicates:
            - Path=/admin/**
            - Path=/web/admin/**