spring:
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # SMTP 服务器端口
    port: 587
    # 邮箱用户名
    username: 782272323@qq.com
    # qq邮箱授权码
    password: szlldqxboucjbcff
    # 编码方式
    default-encoding: UTF-8
    # 配置 SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # 开启日志打印debug
        debug: true
  # nacos 服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.253.110:8848
# 以谁来发送邮件
mail:
  fromMail:
    addr: 782272323@qq.com

dubbo:
  application:
    id: provider-cloud
  scan:
    # dubbo 实现类所在包
    base-packages: lhb.gdms.provider.cloud
  # 协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
  protocol:
    name: dubbo
    port: -1 # 端口为-1时，即是让dubbo自动分配端口
    serialization: kryo # 使用kryo序列化/反序列化工具
  registry:
    address: nacos://172.16.253.110:8848 #注册中心地址，格式为 注册中心组件名://注册中心访问地址
    timeout: 10000 # 10s的超时时间
  provider:
    # 开启轮询负载均衡
    loadbalance: roundrobin

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: lhb.gdms.commons.domain, lhb.gdms.provider.cloud.domain

qiniu:
  accessKey: xx
  secretKey: xx
  # 存储空间名称
  bucket: lhb-msos
  # 访问,根据机房位置从官网获取
  prefix: http://up-z2.qiniup.com
  # 外链域名
  domain: http://img.782272323.cn
  # 存储区域
  zone: huanan

# 阿里云短信配置
aliyun:
  sms:
    accessKeyId: xx
    accessKeySecret: xx
    # 云通信产品api
    product: Dysmsapi
    # 产品域名
    domain: dysmsapi.aliyuncs.com
    # 请求api的名称
    action: SendSms
    regionId: cn-hangzhou
    # 短信签名
    signName: Bin博客
    # 签名算法版本 固定
    version: 2017-05-25
    # 发送日期 支持30天内记录查询 格式yyyyMMdd
    dateFormat: yyyyMMdd
    # 服务结点
    endpointName: cn-hangzhou
    # 短信认证模版code
    templateCode01: SMS_205810298

# 日志级别
logging:
  level:
    lhb.gdms.provider.cloud: debug


